name: openff-openfe
channels:
    - conda-forge
dependencies:
    - python=3.12
    - jupyter
    - jupyter_contrib_nbextensions
    - jupyter_client>=8.5.0  # https://github.com/jupyter/jupyter_client/pull/972
    - openff-toolkit-examples>=0.17.0 # New version needed for NAGL compat.
    - openff-interchange>=0.4.7 # New version needed for NAGL compat.
    - MDAnalysis
    - prolif
    - py3dmol # For 3D visualization of of interactions in prolif
    - openbabel # For conversion of the pdbqt files to sdf (last exercise)
    - rdkit
    - nglview
    - openfe=1.7.0

